const SARKARI_DATA = {
  "lastUpdated": "12:34 AM",
  "lastSyncDate": "28 Sept 2026",
  "trending": [
    {
      "id": "mpesb-teacher-counselling",
      "title": "MPESB Teacher counselling",
      "organization": "MPESB",
      "org": "MPESB",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Teacher",
      "totalPosts": "N/A",
      "posts": "N/A",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "Just Now",
      "timestamp": 1790535894656,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://esb.mp.gov.in/",
      "link": "https://esb.mp.gov.in/",
      "actionUrl": "https://esb.mp.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://esb.mp.gov.in/",
        "officialPdf": "https://esb.mp.gov.in/"
      }
    },
    {
      "id": "bihar-stet-2026-online",
      "title": "Bihar STET 2026 Online",
      "organization": "BSEB",
      "org": "BSEB",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "N/A",
      "posts": "N/A",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "15m ago",
      "timestamp": 1790534994656,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bseb.com/",
      "link": "https://bseb.com/",
      "actionUrl": "https://bseb.com/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://bseb.com/",
        "officialPdf": "https://bseb.com/"
      }
    },
    {
      "id": "icf-apprentice-1010-posts",
      "title": "ICF Apprentice 1010 Posts",
      "organization": "ICF",
      "org": "ICF",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "10th/12th/ITI",
      "totalPosts": "1010",
      "posts": "1010",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "35m ago",
      "timestamp": 1790534094656,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://pb.icf.gov.in/",
      "link": "https://pb.icf.gov.in/",
      "actionUrl": "https://pb.icf.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://pb.icf.gov.in/",
        "officialPdf": "https://pb.icf.gov.in/"
      }
    },
    {
      "id": "rcf-kapurthala-vacancy-734-posts",
      "title": "RCF Kapurthala Vacancy 734 Posts",
      "organization": "RCF Kapurthala",
      "org": "RCF Kapurthala",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "10th + ITI",
      "totalPosts": "734",
      "posts": "734",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "1h ago",
      "timestamp": 1790533194656,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://rcf.indianrailways.gov.in/",
      "link": "https://rcf.indianrailways.gov.in/",
      "actionUrl": "https://rcf.indianrailways.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://rcf.indianrailways.gov.in/",
        "officialPdf": "https://rcf.indianrailways.gov.in/"
      }
    }
  ],
  "latestJobs": [
    {
      "id": "southern-railway-sports-quota-vacancy-2026",
      "title": "Southern Railway Sports Quota Vacancy 2026: 10वीं से ग्रेजुएशन पास खिलाड़ियों के लिए मौका",
      "organization": "Southern Railway",
      "org": "Southern Railway",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "10th to Graduation",
      "totalPosts": "N/A",
      "posts": "N/A",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "Just Now",
      "timestamp": 1790535894657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sr.indianrailways.gov.in/",
      "link": "https://sr.indianrailways.gov.in/",
      "actionUrl": "https://sr.indianrailways.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sr.indianrailways.gov.in/",
        "officialPdf": "https://sr.indianrailways.gov.in/"
      }
    },
    {
      "id": "sbi-bank-specialist-cadre-officer-online-form",
      "title": "SBI Bank Specialist Cadre Officer Online Form : 207 पदों पर भर्ती, जानें?",
      "organization": "SBI",
      "org": "SBI",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Specialist Officer",
      "totalPosts": "207",
      "posts": "207",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "15m ago",
      "timestamp": 1790534994657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://www.sbi.co.in/web/careers",
      "link": "https://www.sbi.co.in/web/careers",
      "actionUrl": "https://www.sbi.co.in/web/careers",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://www.sbi.co.in/web/careers",
        "officialPdf": "https://www.sbi.co.in/web/careers"
      }
    },
    {
      "id": "boi-so-vacancy-2026",
      "title": "BOI SO Vacancy 2026: 205 Specialist Officer पदों पर भर्ती, ₹1.20 लाख तक Salary",
      "organization": "Bank of India",
      "org": "Bank of India",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Specialist Officer",
      "totalPosts": "205",
      "posts": "205",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "35m ago",
      "timestamp": 1790534094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bankofindia.co.in/",
      "link": "https://bankofindia.co.in/",
      "actionUrl": "https://bankofindia.co.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://bankofindia.co.in/",
        "officialPdf": "https://bankofindia.co.in/"
      }
    },
    {
      "id": "rgnau-amethi-vacancy-2026",
      "title": "RGNAU Amethi Vacancy 2026: 10वीं पास से Walk-In Interview का मौका",
      "organization": "RGNAU Amethi",
      "org": "RGNAU Amethi",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "10th Pass",
      "totalPosts": "N/A",
      "posts": "N/A",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "1h ago",
      "timestamp": 1790533194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://rgnau.ac.in/",
      "link": "https://rgnau.ac.in/",
      "actionUrl": "https://rgnau.ac.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://rgnau.ac.in/",
        "officialPdf": "https://rgnau.ac.in/"
      }
    },
    {
      "id": "hppsc-ado-vacancy-2026",
      "title": "HPPSC ADO Vacancy 2026:  ₹29,500 महीना, जानें योग्यता और आवेदन प्रक्रिया",
      "organization": "HPPSC",
      "org": "HPPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "N/A",
      "posts": "N/A",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "2h ago",
      "timestamp": 1790532294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://hppsc.hp.gov.in/",
      "link": "https://hppsc.hp.gov.in/",
      "actionUrl": "https://hppsc.hp.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://hppsc.hp.gov.in/",
        "officialPdf": "https://hppsc.hp.gov.in/"
      }
    },
    {
      "id": "bknmu-non-teaching-vacancy-2026",
      "title": "BKNMU Non-Teaching Vacancy 2026: 11 पदों पर भर्ती, 16 अक्टूबर तक करें आवेदन",
      "organization": "BKNMU",
      "org": "BKNMU",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "11",
      "posts": "11",
      "status": "Active",
      "lastDate": "16 Oct 2026",
      "deadlineLabel": "Last Date: 16 Oct 2026",
      "date": "16 Oct 2026",
      "timeBadge": "4h ago",
      "timestamp": 1790531394657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bknmu.edu.in/",
      "link": "https://bknmu.edu.in/",
      "actionUrl": "https://bknmu.edu.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://bknmu.edu.in/",
        "officialPdf": "https://bknmu.edu.in/"
      }
    },
    {
      "id": "gtbh-delhi-senior-resident-vacancy-2026",
      "title": "GTBH Delhi Senior Resident Vacancy 2026: 89 पदों पर भर्ती, ₹67,700 Salary",
      "organization": "GTBH Delhi",
      "org": "GTBH Delhi",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "89",
      "posts": "89",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "Today",
      "timestamp": 1790530494657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "http://gtbh.delhigovt.nic.in/",
      "link": "http://gtbh.delhigovt.nic.in/",
      "actionUrl": "http://gtbh.delhigovt.nic.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "http://gtbh.delhigovt.nic.in/",
        "officialPdf": "http://gtbh.delhigovt.nic.in/"
      }
    },
    {
      "id": "sai-assistant-vacancy-2026",
      "title": "SAI Assistant Vacancy 2026 : 91 पदों पर भर्ती, 15 अक्टूबर तक करें आवेदन",
      "organization": "SAI",
      "org": "SAI",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "91",
      "posts": "91",
      "status": "Active",
      "lastDate": "15 Oct 2026",
      "deadlineLabel": "Last Date: 15 Oct 2026",
      "date": "15 Oct 2026",
      "timeBadge": "Yesterday",
      "timestamp": 1790529594657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sportsauthorityofindia.nic.in/",
      "link": "https://sportsauthorityofindia.nic.in/",
      "actionUrl": "https://sportsauthorityofindia.nic.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sportsauthorityofindia.nic.in/",
        "officialPdf": "https://sportsauthorityofindia.nic.in/"
      }
    },
    {
      "id": "psssb-vacancy-2026",
      "title": "PSSSB Vacancy 2026: Driver, Clerk समेत 70 पदों पर निकली भर्ती, आवेदन शुरू",
      "organization": "PSSSB",
      "org": "PSSSB",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Driver, Clerk",
      "totalPosts": "70",
      "posts": "70",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "Just Now",
      "timestamp": 1790528694657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sssb.punjab.gov.in/",
      "link": "https://sssb.punjab.gov.in/",
      "actionUrl": "https://sssb.punjab.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sssb.punjab.gov.in/",
        "officialPdf": "https://sssb.punjab.gov.in/"
      }
    },
    {
      "id": "upsc-vacancy-2026",
      "title": "UPSC Vacancy 2026: 13 पदों पर मौका, ऑनलाइन आवेदन शुरू",
      "organization": "UPSC",
      "org": "UPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "13",
      "posts": "13",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "15m ago",
      "timestamp": 1790527794657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsc.gov.in/",
      "link": "https://upsc.gov.in/",
      "actionUrl": "https://upsc.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://upsc.gov.in/",
        "officialPdf": "https://upsc.gov.in/"
      }
    },
    {
      "id": "btsc-food-safety-officer-bharti-2026",
      "title": "BTSC Food Safety Officer Bharti 2026 : 105 पदों पर भर्ती, आवेदन शुरू",
      "organization": "BTSC",
      "org": "BTSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "105",
      "posts": "105",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "35m ago",
      "timestamp": 1790526894657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://btsc.bih.nic.in/",
      "link": "https://btsc.bih.nic.in/",
      "actionUrl": "https://btsc.bih.nic.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://btsc.bih.nic.in/",
        "officialPdf": "https://btsc.bih.nic.in/"
      }
    },
    {
      "id": "bpsc-tre-4-vacancy-2026",
      "title": "BPSC TRE 4 Vacancy 2026 : 32,388 शिक्षक पदों पर होगी बंपर भर्ती, जानें?",
      "organization": "BPSC",
      "org": "BPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Teacher",
      "totalPosts": "32388",
      "posts": "32388",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "1h ago",
      "timestamp": 1790525994657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bpsc.bih.nic.in/",
      "link": "https://bpsc.bih.nic.in/",
      "actionUrl": "https://bpsc.bih.nic.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://bpsc.bih.nic.in/",
        "officialPdf": "https://bpsc.bih.nic.in/"
      }
    },
    {
      "id": "pmbi-vacancy-2026",
      "title": "PMBI Vacancy 2026 : 178 पदों पर भर्ती, ₹1.58 लाख तक सैलरी",
      "organization": "PMBI",
      "org": "PMBI",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "178",
      "posts": "178",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "2h ago",
      "timestamp": 1790525094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://janaushadhi.gov.in/",
      "link": "https://janaushadhi.gov.in/",
      "actionUrl": "https://janaushadhi.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://janaushadhi.gov.in/",
        "officialPdf": "https://janaushadhi.gov.in/"
      }
    },
    {
      "id": "rajasthan-safai-karmachari-bharti-2026",
      "title": "Rajasthan Safai Karmachari Bharti 2026: 24,752 पदों पर बंपर भर्ती, 15 अगस्त से आवेदन शुरू",
      "organization": "Rajasthan Local Self Government Department",
      "org": "Rajasthan Local Self Government Department",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "N/A",
      "totalPosts": "24752",
      "posts": "24752",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "4h ago",
      "timestamp": 1790524194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://lsg.urban.rajasthan.gov.in/",
      "link": "https://lsg.urban.rajasthan.gov.in/",
      "actionUrl": "https://lsg.urban.rajasthan.gov.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://lsg.urban.rajasthan.gov.in/",
        "officialPdf": "https://lsg.urban.rajasthan.gov.in/"
      }
    },
    {
      "id": "bank-of-baroda-so-vacancy-2026",
      "title": "Bank of Baroda SO Vacancy 2026: 1100 पदों पर भर्ती, Graduate उम्मीदवारों के लिए मौका",
      "organization": "Bank of Baroda",
      "org": "Bank of Baroda",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "1100",
      "posts": "1100",
      "status": "Active",
      "lastDate": "Active Now",
      "deadlineLabel": "Last Date: Active Now",
      "date": "Active Now",
      "timeBadge": "Today",
      "timestamp": 1790523294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bankofbaroda.in/",
      "link": "https://bankofbaroda.in/",
      "actionUrl": "https://bankofbaroda.in/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://bankofbaroda.in/",
        "officialPdf": "https://bankofbaroda.in/"
      }
    }
  ],
  "admitCards": [
    {
      "id": "upsssc-pet-revised-exam-date-2026",
      "title": "UPSSSC PET Revised Exam Date 2026",
      "organization": "UPSSSC",
      "org": "UPSSSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "Just Now",
      "timestamp": 1790535894657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsssc.gov.in/",
      "link": "https://upsssc.gov.in/",
      "actionUrl": "https://upsssc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://upsssc.gov.in/",
        "officialPdf": "https://upsssc.gov.in/"
      }
    },
    {
      "id": "ssc-delhi-police-driver-physical-admit-card-2026",
      "title": "SSC Delhi Police Driver Physical Admit Card 2026",
      "organization": "SSC Delhi Police",
      "org": "SSC Delhi Police",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "15m ago",
      "timestamp": 1790534994657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://ssc.gov.in/",
      "link": "https://ssc.gov.in/",
      "actionUrl": "https://ssc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://ssc.gov.in/",
        "officialPdf": "https://ssc.gov.in/"
      }
    },
    {
      "id": "aiims-norcet-11th-stage-ii-admit-card-2026",
      "title": "AIIMS NORCET 11th Stage-II Admit Card 2026",
      "organization": "AIIMS",
      "org": "AIIMS",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "35m ago",
      "timestamp": 1790534094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://www.aiimsexams.ac.in/",
      "link": "https://www.aiimsexams.ac.in/",
      "actionUrl": "https://www.aiimsexams.ac.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://www.aiimsexams.ac.in/",
        "officialPdf": "https://www.aiimsexams.ac.in/"
      }
    },
    {
      "id": "upsssc-junior-assistant-typing-test-exam-date-2026",
      "title": "UPSSSC Junior Assistant Typing Test Exam Date 2026",
      "organization": "UPSSSC",
      "org": "UPSSSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "1h ago",
      "timestamp": 1790533194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsssc.gov.in/",
      "link": "https://upsssc.gov.in/",
      "actionUrl": "https://upsssc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://upsssc.gov.in/",
        "officialPdf": "https://upsssc.gov.in/"
      }
    },
    {
      "id": "ibps-po-mt-mains-admit-card-2026",
      "title": "IBPS PO & MT Mains Admit Card 2026",
      "organization": "IBPS",
      "org": "IBPS",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "2h ago",
      "timestamp": 1790532294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://ibps.in/",
      "link": "https://ibps.in/",
      "actionUrl": "https://ibps.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://ibps.in/",
        "officialPdf": "https://ibps.in/"
      }
    },
    {
      "id": "up-police-constable-pet-exam-schedule-2026",
      "title": "UP Police Constable PET Exam Schedule 2026",
      "organization": "UP Police",
      "org": "UP Police",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "Active Now",
      "deadlineLabel": "Exam Date: Active Now",
      "date": "Active Now",
      "timeBadge": "4h ago",
      "timestamp": 1790531394657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://uppbpb.gov.in/",
      "link": "https://uppbpb.gov.in/",
      "actionUrl": "https://uppbpb.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://uppbpb.gov.in/",
        "officialPdf": "https://uppbpb.gov.in/"
      }
    },
    {
      "id": "hprca-joa-it-admit-card-2026",
      "title": "HPRCA JOA IT Admit Card 2026",
      "organization": "HPRCA",
      "org": "HPRCA",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "Today",
      "timestamp": 1790530494657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://hppsc.hp.gov.in/",
      "link": "https://hppsc.hp.gov.in/",
      "actionUrl": "https://hppsc.hp.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://hppsc.hp.gov.in/",
        "officialPdf": "https://hppsc.hp.gov.in/"
      }
    },
    {
      "id": "bank-of-baroda-local-bank-officer-lbo-exam-date-2026",
      "title": "Bank of Baroda Local Bank Officer LBO Exam Date 2026",
      "organization": "Bank of Baroda",
      "org": "Bank of Baroda",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "Yesterday",
      "timestamp": 1790529594657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bankofbaroda.in/",
      "link": "https://bankofbaroda.in/",
      "actionUrl": "https://bankofbaroda.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://bankofbaroda.in/",
        "officialPdf": "https://bankofbaroda.in/"
      }
    },
    {
      "id": "nainital-bank-specialist-officer-admit-card-2026",
      "title": "Nainital Bank Specialist Officer Admit Card 2026",
      "organization": "Nainital Bank",
      "org": "Nainital Bank",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "Just Now",
      "timestamp": 1790528694657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://www.nainitalbank.co.in/",
      "link": "https://www.nainitalbank.co.in/",
      "actionUrl": "https://www.nainitalbank.co.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://www.nainitalbank.co.in/",
        "officialPdf": "https://www.nainitalbank.co.in/"
      }
    },
    {
      "id": "upsssc-forensic-science-laboratory-admit-card-2026",
      "title": "UPSSSC Forensic Science Laboratory Admit Card 2026",
      "organization": "UPSSSC",
      "org": "UPSSSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "15m ago",
      "timestamp": 1790527794657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsssc.gov.in/",
      "link": "https://upsssc.gov.in/",
      "actionUrl": "https://upsssc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://upsssc.gov.in/",
        "officialPdf": "https://upsssc.gov.in/"
      }
    },
    {
      "id": "upsssc-forest-guard-wildlife-guard-admit-card-2026",
      "title": "UPSSSC Forest Guard / Wildlife Guard Admit Card 2026",
      "organization": "UPSSSC",
      "org": "UPSSSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "35m ago",
      "timestamp": 1790526894657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsssc.gov.in/",
      "link": "https://upsssc.gov.in/",
      "actionUrl": "https://upsssc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://upsssc.gov.in/",
        "officialPdf": "https://upsssc.gov.in/"
      }
    },
    {
      "id": "opsc-assistant-horticulture-officer-admit-card-2026",
      "title": "OPSC Assistant Horticulture Officer Admit Card 2026",
      "organization": "OPSC",
      "org": "OPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "1h ago",
      "timestamp": 1790525994657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://opsc.gov.in/",
      "link": "https://opsc.gov.in/",
      "actionUrl": "https://opsc.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://opsc.gov.in/",
        "officialPdf": "https://opsc.gov.in/"
      }
    },
    {
      "id": "uppsc-pcs-interview-letter-2026",
      "title": "UPPSC PCS Interview Letter 2026",
      "organization": "UPPSC",
      "org": "UPPSC",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "12th Pass",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "2h ago",
      "timestamp": 1790525094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://uppsc.up.nic.in/",
      "link": "https://uppsc.up.nic.in/",
      "actionUrl": "https://uppsc.up.nic.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://uppsc.up.nic.in/",
        "officialPdf": "https://uppsc.up.nic.in/"
      }
    },
    {
      "id": "utet-admit-card-2026",
      "title": "UTET Admit Card 2026",
      "organization": "UTET",
      "org": "UTET",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "4h ago",
      "timestamp": 1790524194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://ubse.uk.gov.in/",
      "link": "https://ubse.uk.gov.in/",
      "actionUrl": "https://ubse.uk.gov.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://ubse.uk.gov.in/",
        "officialPdf": "https://ubse.uk.gov.in/"
      }
    },
    {
      "id": "bpsc-project-manager-pre-exam-date-2026",
      "title": "BPSC Project Manager Pre Exam Date 2026",
      "organization": "BPSC",
      "org": "BPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Released",
      "lastDate": "OUT",
      "deadlineLabel": "Exam Date: OUT",
      "date": "OUT",
      "timeBadge": "Today",
      "timestamp": 1790523294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://bpsc.bih.nic.in/",
      "link": "https://bpsc.bih.nic.in/",
      "actionUrl": "https://bpsc.bih.nic.in/",
      "links": {
        "actionLabel": "Download Admit Card",
        "actionUrl": "https://bpsc.bih.nic.in/",
        "officialPdf": "https://bpsc.bih.nic.in/"
      }
    }
  ],
  "results": [
    {
      "id": "nta-csir-ugc-net-e-certificate-2026",
      "title": "NTA CSIR UGC NET E Certificate 2026",
      "organization": "NTA CSIR UGC NET",
      "org": "NTA CSIR UGC NET",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "Just Now",
      "timestamp": 1790535894657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://csirnet.nta.ac.in/",
      "link": "https://csirnet.nta.ac.in/",
      "actionUrl": "https://csirnet.nta.ac.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://csirnet.nta.ac.in/",
        "officialPdf": "https://csirnet.nta.ac.in/"
      }
    },
    {
      "id": "csir-neist-driver-and-mts-result-2026",
      "title": "CSIR NEIST Driver and MTS Result 2026",
      "organization": "CSIR NEIST",
      "org": "CSIR NEIST",
      "category": "10th Pass",
      "tag": "10th Pass",
      "qualification": "10th Pass",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "15m ago",
      "timestamp": 1790534994657,
      "isNew": true,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://neist.res.in/",
      "link": "https://neist.res.in/",
      "actionUrl": "https://neist.res.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://neist.res.in/",
        "officialPdf": "https://neist.res.in/"
      }
    },
    {
      "id": "beml-executive-result-2026",
      "title": "BEML Executive Result 2026",
      "organization": "BEML",
      "org": "BEML",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "OUT",
      "deadlineLabel": "Declared: OUT",
      "date": "OUT",
      "timeBadge": "35m ago",
      "timestamp": 1790534094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://www.bemlindia.in/",
      "link": "https://www.bemlindia.in/",
      "actionUrl": "https://www.bemlindia.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://www.bemlindia.in/",
        "officialPdf": "https://www.bemlindia.in/"
      }
    },
    {
      "id": "hal-dt-and-mt-final-result-2026",
      "title": "HAL DT and MT Final Result 2026",
      "organization": "HAL",
      "org": "HAL",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "1h ago",
      "timestamp": 1790533194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://hal-india.co.in/",
      "link": "https://hal-india.co.in/",
      "actionUrl": "https://hal-india.co.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://hal-india.co.in/",
        "officialPdf": "https://hal-india.co.in/"
      }
    },
    {
      "id": "sssb-punjab-junior-scale-stenographer-result-2026",
      "title": "SSSB Punjab Junior Scale Stenographer Result 2026",
      "organization": "SSSB Punjab",
      "org": "SSSB Punjab",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "12th Pass",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "2h ago",
      "timestamp": 1790532294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sssb.punjab.gov.in/",
      "link": "https://sssb.punjab.gov.in/",
      "actionUrl": "https://sssb.punjab.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://sssb.punjab.gov.in/",
        "officialPdf": "https://sssb.punjab.gov.in/"
      }
    },
    {
      "id": "upsssc-assistant-store-keeper-final-result-2026",
      "title": "UPSSSC Assistant Store Keeper Final Result 2026",
      "organization": "UPSSSC",
      "org": "UPSSSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "4h ago",
      "timestamp": 1790531394657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://upsssc.gov.in/",
      "link": "https://upsssc.gov.in/",
      "actionUrl": "https://upsssc.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://upsssc.gov.in/",
        "officialPdf": "https://upsssc.gov.in/"
      }
    },
    {
      "id": "hprca-teacher-psychology-final-result-2026",
      "title": "HPRCA Teacher Psychology Final Result 2026",
      "organization": "HPRCA",
      "org": "HPRCA",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "Today",
      "timestamp": 1790530494657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://hppsc.hp.gov.in/",
      "link": "https://hppsc.hp.gov.in/",
      "actionUrl": "https://hppsc.hp.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://hppsc.hp.gov.in/",
        "officialPdf": "https://hppsc.hp.gov.in/"
      }
    },
    {
      "id": "wbp-constable-final-result-2026",
      "title": "WBP Constable Final Result 2026",
      "organization": "WBP",
      "org": "WBP",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "Yesterday",
      "timestamp": 1790529594657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://wbpolice.gov.in/",
      "link": "https://wbpolice.gov.in/",
      "actionUrl": "https://wbpolice.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://wbpolice.gov.in/",
        "officialPdf": "https://wbpolice.gov.in/"
      }
    },
    {
      "id": "rbi-assistant-mains-result-2026",
      "title": "RBI Assistant Mains Result 2026",
      "organization": "RBI",
      "org": "RBI",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "Just Now",
      "timestamp": 1790528694657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://rbi.org.in/",
      "link": "https://rbi.org.in/",
      "actionUrl": "https://rbi.org.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://rbi.org.in/",
        "officialPdf": "https://rbi.org.in/"
      }
    },
    {
      "id": "nta-ugc-net-june-certificate-2026",
      "title": "NTA UGC NET June Certificate 2026",
      "organization": "NTA UGC NET",
      "org": "NTA UGC NET",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Active Now",
      "deadlineLabel": "Declared: Active Now",
      "date": "Active Now",
      "timeBadge": "15m ago",
      "timestamp": 1790527794657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://ugcnet.nta.ac.in/",
      "link": "https://ugcnet.nta.ac.in/",
      "actionUrl": "https://ugcnet.nta.ac.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://ugcnet.nta.ac.in/",
        "officialPdf": "https://ugcnet.nta.ac.in/"
      }
    },
    {
      "id": "neet-pg-result-2026",
      "title": "NEET PG Result 2026",
      "organization": "NEET PG",
      "org": "NEET PG",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "35m ago",
      "timestamp": 1790526894657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://natboard.edu.in/",
      "link": "https://natboard.edu.in/",
      "actionUrl": "https://natboard.edu.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://natboard.edu.in/",
        "officialPdf": "https://natboard.edu.in/"
      }
    },
    {
      "id": "rpsc-junior-legal-officer-result-2026",
      "title": "RPSC Junior Legal Officer Result 2026",
      "organization": "RPSC",
      "org": "RPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "1h ago",
      "timestamp": 1790525994657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://rpsc.rajasthan.gov.in/",
      "link": "https://rpsc.rajasthan.gov.in/",
      "actionUrl": "https://rpsc.rajasthan.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://rpsc.rajasthan.gov.in/",
        "officialPdf": "https://rpsc.rajasthan.gov.in/"
      }
    },
    {
      "id": "mppsc-assistant-professor-commerce-result-2026",
      "title": "MPPSC Assistant Professor Commerce Result 2026",
      "organization": "MPPSC",
      "org": "MPPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "2h ago",
      "timestamp": 1790525094657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://mppsc.mp.gov.in/",
      "link": "https://mppsc.mp.gov.in/",
      "actionUrl": "https://mppsc.mp.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://mppsc.mp.gov.in/",
        "officialPdf": "https://mppsc.mp.gov.in/"
      }
    },
    {
      "id": "ibps-crp-po-mt-xvi-pre-result-2026",
      "title": "IBPS CRP PO MT XVI Pre Result 2026",
      "organization": "IBPS",
      "org": "IBPS",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "4h ago",
      "timestamp": 1790524194657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://ibps.in/",
      "link": "https://ibps.in/",
      "actionUrl": "https://ibps.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://ibps.in/",
        "officialPdf": "https://ibps.in/"
      }
    },
    {
      "id": "rpsc-assistant-professor-result-2026",
      "title": "RPSC Assistant Professor Result 2026",
      "organization": "RPSC",
      "org": "RPSC",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Official Notice",
      "posts": "Check Official Notice",
      "status": "Declared",
      "lastDate": "Released",
      "deadlineLabel": "Declared: Released",
      "date": "Released",
      "timeBadge": "Today",
      "timestamp": 1790523294657,
      "isNew": false,
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://rpsc.rajasthan.gov.in/",
      "link": "https://rpsc.rajasthan.gov.in/",
      "actionUrl": "https://rpsc.rajasthan.gov.in/",
      "links": {
        "actionLabel": "Check Result",
        "actionUrl": "https://rpsc.rajasthan.gov.in/",
        "officialPdf": "https://rpsc.rajasthan.gov.in/"
      }
    }
  ],
  "answerKeys": [
    {
      "title": "SSC Stenographer Grade C & D Tentative Key 2026",
      "actionUrl": "https://ssc.gov.in",
      "category": "12th Pass",
      "timeBadge": "2h ago",
      "deadlineLabel": "Objection till 02 Oct",
      "link": "https://ssc.gov.in"
    },
    {
      "title": "RRB NTPC CEN 07/2025 Answer Key 2026",
      "actionUrl": "https://rrbapply.gov.in",
      "category": "12th Pass",
      "timeBadge": "5h ago",
      "deadlineLabel": "Objection till 05 Oct",
      "link": "https://rrbapply.gov.in"
    }
  ],
  "syllabus": [
    {
      "title": "UP Police Sub-Inspector (SI) Exam Pattern 2026",
      "actionUrl": "https://uppbpb.gov.in",
      "category": "Police / Defense",
      "timeBadge": "1d ago",
      "deadlineLabel": "Updated 2026 Syllabus",
      "link": "https://uppbpb.gov.in"
    },
    {
      "title": "RRB NTPC Graduate & UG Exam Syllabus 2026",
      "actionUrl": "https://rrbapply.gov.in",
      "category": "Graduate",
      "timeBadge": "2d ago",
      "deadlineLabel": "Official CBT Scheme",
      "link": "https://rrbapply.gov.in"
    }
  ],
  "admissions": [
    {
      "title": "MCC NEET UG Counselling Round Registration",
      "actionUrl": "https://mcc.nic.in",
      "category": "Graduate",
      "timeBadge": "Today",
      "deadlineLabel": "Last Date: 08 Oct 2026",
      "link": "https://mcc.nic.in"
    },
    {
      "title": "NTA CUET PG Admission Schedule 2026",
      "actionUrl": "https://cuet.nta.nic.in",
      "category": "Graduate",
      "timeBadge": "Yesterday",
      "deadlineLabel": "Registration Active",
      "link": "https://cuet.nta.nic.in"
    }
  ]
};

window.SARKARI_DATA = SARKARI_DATA;