const SARKARI_DATA = {
  "trending": [
    {
      "id": "mpesb-primary-teacher-counselling-2026",
      "title": "MPESB Teacher counselling",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/mpesb-primary-teacher-counselling-2026/",
      "link": "https://sarkaricsc.com/mpesb-primary-teacher-counselling-2026/",
      "actionUrl": "https://sarkaricsc.com/mpesb-primary-teacher-counselling-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/mpesb-primary-teacher-counselling-2026/",
        "officialPdf": "https://sarkaricsc.com/mpesb-primary-teacher-counselling-2026/"
      }
    },
    {
      "id": "bihar-stet-2026-online-form",
      "title": "Bihar STET 2026 Online",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bihar-stet-2026-online-form/",
      "link": "https://sarkaricsc.com/bihar-stet-2026-online-form/",
      "actionUrl": "https://sarkaricsc.com/bihar-stet-2026-online-form/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bihar-stet-2026-online-form/",
        "officialPdf": "https://sarkaricsc.com/bihar-stet-2026-online-form/"
      }
    },
    {
      "id": "icf-apprentice-vacancy-2026",
      "title": "ICF Apprentice 1010 Posts",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "1010",
      "posts": "1010",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/icf-apprentice-vacancy-2026/",
      "link": "https://sarkaricsc.com/icf-apprentice-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/icf-apprentice-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/icf-apprentice-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/icf-apprentice-vacancy-2026/"
      }
    },
    {
      "id": "rcf-kapurthala-vacancy-2026",
      "title": "RCF Kapurthala Vacancy 734 Posts",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "734",
      "posts": "734",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rcf-kapurthala-vacancy-2026/",
      "link": "https://sarkaricsc.com/rcf-kapurthala-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/rcf-kapurthala-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rcf-kapurthala-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/rcf-kapurthala-vacancy-2026/"
      }
    }
  ],
  "latestJobs": [
    {
      "id": "southern-railway-sports-quota-vacancy-2026",
      "title": "Southern Railway Sports Quota Vacancy 2026: 10वीं से ग्रेजुएशन पास खिलाड़ियों के लिए मौका",
      "organization": "Railway Recruitment Board (RRB)",
      "org": "Railway Recruitment Board (RRB)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/southern-railway-sports-quota-vacancy-2026/",
      "link": "https://sarkaricsc.com/southern-railway-sports-quota-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/southern-railway-sports-quota-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/southern-railway-sports-quota-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/southern-railway-sports-quota-vacancy-2026/"
      }
    },
    {
      "id": "sbi-bank-specialist-cadre-officer-online-form",
      "title": "SBI Bank Specialist Cadre Officer Online Form : 207 पदों पर भर्ती, जानें?",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "207",
      "posts": "207",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/sbi-bank-specialist-cadre-officer-online-form/",
      "link": "https://sarkaricsc.com/sbi-bank-specialist-cadre-officer-online-form/",
      "actionUrl": "https://sarkaricsc.com/sbi-bank-specialist-cadre-officer-online-form/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/sbi-bank-specialist-cadre-officer-online-form/",
        "officialPdf": "https://sarkaricsc.com/sbi-bank-specialist-cadre-officer-online-form/"
      }
    },
    {
      "id": "boi-so-vacancy-2026",
      "title": "BOI SO Vacancy 2026: 205 Specialist Officer पदों पर भर्ती, ₹1.20 लाख तक Salary",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "205",
      "posts": "205",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/boi-so-vacancy-2026/",
      "link": "https://sarkaricsc.com/boi-so-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/boi-so-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/boi-so-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/boi-so-vacancy-2026/"
      }
    },
    {
      "id": "rgnau-amethi-vacancy-2026",
      "title": "RGNAU Amethi Vacancy 2026: 10वीं पास से Walk-In Interview का मौका",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "12th Pass",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rgnau-amethi-vacancy-2026/",
      "link": "https://sarkaricsc.com/rgnau-amethi-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/rgnau-amethi-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rgnau-amethi-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/rgnau-amethi-vacancy-2026/"
      }
    },
    {
      "id": "hppsc-ado-vacancy-2026",
      "title": "HPPSC ADO Vacancy 2026: ₹29,500 महीना, जानें योग्यता और आवेदन प्रक्रिया",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/hppsc-ado-vacancy-2026/",
      "link": "https://sarkaricsc.com/hppsc-ado-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/hppsc-ado-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/hppsc-ado-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/hppsc-ado-vacancy-2026/"
      }
    },
    {
      "id": "bknmu-non-teaching-vacancy-2026",
      "title": "BKNMU Non-Teaching Vacancy 2026: 11 पदों पर भर्ती, 16 अक्टूबर तक करें आवेदन",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "11",
      "posts": "11",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bknmu-non-teaching-vacancy-2026/",
      "link": "https://sarkaricsc.com/bknmu-non-teaching-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/bknmu-non-teaching-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bknmu-non-teaching-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/bknmu-non-teaching-vacancy-2026/"
      }
    },
    {
      "id": "gtbh-delhi-senior-resident-vacancy-2026",
      "title": "GTBH Delhi Senior Resident Vacancy 2026: 89 पदों पर भर्ती, ₹67,700 Salary",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "89",
      "posts": "89",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/gtbh-delhi-senior-resident-vacancy-2026/",
      "link": "https://sarkaricsc.com/gtbh-delhi-senior-resident-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/gtbh-delhi-senior-resident-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/gtbh-delhi-senior-resident-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/gtbh-delhi-senior-resident-vacancy-2026/"
      }
    },
    {
      "id": "sai-assistant-vacancy-2026",
      "title": "SAI Assistant Vacancy 2026 : 91 पदों पर भर्ती, 15 अक्टूबर तक करें आवेदन",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "91",
      "posts": "91",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/sai-assistant-vacancy-2026/",
      "link": "https://sarkaricsc.com/sai-assistant-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/sai-assistant-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/sai-assistant-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/sai-assistant-vacancy-2026/"
      }
    },
    {
      "id": "psssb-vacancy-2026-out",
      "title": "PSSSB Vacancy 2026: Driver, Clerk समेत 70 पदों पर निकली भर्ती, आवेदन शुरू",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "70",
      "posts": "70",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/psssb-vacancy-2026-out/",
      "link": "https://sarkaricsc.com/psssb-vacancy-2026-out/",
      "actionUrl": "https://sarkaricsc.com/psssb-vacancy-2026-out/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/psssb-vacancy-2026-out/",
        "officialPdf": "https://sarkaricsc.com/psssb-vacancy-2026-out/"
      }
    },
    {
      "id": "upsc-vacancy-2026-new",
      "title": "UPSC Vacancy 2026: 13 पदों पर मौका, ऑनलाइन आवेदन शुरू",
      "organization": "Union Public Service Commission (UPSC)",
      "org": "Union Public Service Commission (UPSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "13",
      "posts": "13",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsc-vacancy-2026-new/",
      "link": "https://sarkaricsc.com/upsc-vacancy-2026-new/",
      "actionUrl": "https://sarkaricsc.com/upsc-vacancy-2026-new/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsc-vacancy-2026-new/",
        "officialPdf": "https://sarkaricsc.com/upsc-vacancy-2026-new/"
      }
    },
    {
      "id": "btsc-food-safety-officer-bharti-2026",
      "title": "BTSC Food Safety Officer Bharti 2026 : 105 पदों पर भर्ती, आवेदन शुरू",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "105",
      "posts": "105",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/btsc-food-safety-officer-bharti-2026/",
      "link": "https://sarkaricsc.com/btsc-food-safety-officer-bharti-2026/",
      "actionUrl": "https://sarkaricsc.com/btsc-food-safety-officer-bharti-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/btsc-food-safety-officer-bharti-2026/",
        "officialPdf": "https://sarkaricsc.com/btsc-food-safety-officer-bharti-2026/"
      }
    },
    {
      "id": "bpsc-tre-4-vacancy-2026",
      "title": "BPSC TRE 4 Vacancy 2026 : 32,388 शिक्षक पदों पर होगी बंपर भर्ती, जानें?",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "32,388",
      "posts": "32,388",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bpsc-tre-4-vacancy-2026/",
      "link": "https://sarkaricsc.com/bpsc-tre-4-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/bpsc-tre-4-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bpsc-tre-4-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/bpsc-tre-4-vacancy-2026/"
      }
    },
    {
      "id": "pmbi-vacancy-2026",
      "title": "PMBI Vacancy 2026 : 178 पदों पर भर्ती, ₹1.58 लाख तक सैलरी",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "178",
      "posts": "178",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/pmbi-vacancy-2026/",
      "link": "https://sarkaricsc.com/pmbi-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/pmbi-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/pmbi-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/pmbi-vacancy-2026/"
      }
    },
    {
      "id": "rajasthan-safai-karmachari-bharti-2026",
      "title": "Rajasthan Safai Karmachari Bharti 2026: 24,752 पदों पर बंपर भर्ती, 15 अगस्त से आवेदन शुरू",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "24,752",
      "posts": "24,752",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rajasthan-safai-karmachari-bharti-2026/",
      "link": "https://sarkaricsc.com/rajasthan-safai-karmachari-bharti-2026/",
      "actionUrl": "https://sarkaricsc.com/rajasthan-safai-karmachari-bharti-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rajasthan-safai-karmachari-bharti-2026/",
        "officialPdf": "https://sarkaricsc.com/rajasthan-safai-karmachari-bharti-2026/"
      }
    },
    {
      "id": "bank-of-baroda-so-vacancy-2026",
      "title": "Bank of Baroda SO Vacancy 2026: 1100 पदों पर भर्ती, Graduate उम्मीदवारों के लिए मौका",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "1100",
      "posts": "1100",
      "status": "Active",
      "lastDate": "Active Now",
      "date": "Active Now",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bank-of-baroda-so-vacancy-2026/",
      "link": "https://sarkaricsc.com/bank-of-baroda-so-vacancy-2026/",
      "actionUrl": "https://sarkaricsc.com/bank-of-baroda-so-vacancy-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bank-of-baroda-so-vacancy-2026/",
        "officialPdf": "https://sarkaricsc.com/bank-of-baroda-so-vacancy-2026/"
      }
    }
  ],
  "admitCards": [
    {
      "id": "upsssc-pet-revised-exam-date-2026",
      "title": "UPSSSC PET Revised Exam Date 2026:- OUT",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsssc-pet-revised-exam-date-2026/",
      "link": "https://sarkaricsc.com/upsssc-pet-revised-exam-date-2026/",
      "actionUrl": "https://sarkaricsc.com/upsssc-pet-revised-exam-date-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsssc-pet-revised-exam-date-2026/",
        "officialPdf": "https://sarkaricsc.com/upsssc-pet-revised-exam-date-2026/"
      }
    },
    {
      "id": "ssc-delhi-police-driver-physical-admit-card-2026",
      "title": "SSC Delhi Police Driver Physical Admit Card 2026:- OUT",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/ssc-delhi-police-driver-physical-admit-card-2026/",
      "link": "https://sarkaricsc.com/ssc-delhi-police-driver-physical-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/ssc-delhi-police-driver-physical-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/ssc-delhi-police-driver-physical-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/ssc-delhi-police-driver-physical-admit-card-2026/"
      }
    },
    {
      "id": "aiims-norcet-11th-stage-ii-admit-card-2026",
      "title": "AIIMS NORCET 11th Stage-II Admit Card 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/aiims-norcet-11th-stage-ii-admit-card-2026/",
      "link": "https://sarkaricsc.com/aiims-norcet-11th-stage-ii-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/aiims-norcet-11th-stage-ii-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/aiims-norcet-11th-stage-ii-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/aiims-norcet-11th-stage-ii-admit-card-2026/"
      }
    },
    {
      "id": "upsssc-junior-assistant-typing-test-exam-date-2026-out",
      "title": "UPSSSC Junior Assistant Typing Test Exam Date 2026:- OUT",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsssc-junior-assistant-typing-test-exam-date-2026-out/",
      "link": "https://sarkaricsc.com/upsssc-junior-assistant-typing-test-exam-date-2026-out/",
      "actionUrl": "https://sarkaricsc.com/upsssc-junior-assistant-typing-test-exam-date-2026-out/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsssc-junior-assistant-typing-test-exam-date-2026-out/",
        "officialPdf": "https://sarkaricsc.com/upsssc-junior-assistant-typing-test-exam-date-2026-out/"
      }
    },
    {
      "id": "ibps-po-mt-mains-admit-card-2026",
      "title": "IBPS PO & MT Mains Admit Card 2026:- OUT",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/ibps-po-mt-mains-admit-card-2026/",
      "link": "https://sarkaricsc.com/ibps-po-mt-mains-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/ibps-po-mt-mains-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/ibps-po-mt-mains-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/ibps-po-mt-mains-admit-card-2026/"
      }
    },
    {
      "id": "up-police-constable-pet-exam-schedule-2026",
      "title": "UP Police Constable PET Exam Schedule 2026",
      "organization": "State Police Recruitment Board",
      "org": "State Police Recruitment Board",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/up-police-constable-pet-exam-schedule-2026/",
      "link": "https://sarkaricsc.com/up-police-constable-pet-exam-schedule-2026/",
      "actionUrl": "https://sarkaricsc.com/up-police-constable-pet-exam-schedule-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/up-police-constable-pet-exam-schedule-2026/",
        "officialPdf": "https://sarkaricsc.com/up-police-constable-pet-exam-schedule-2026/"
      }
    },
    {
      "id": "hprca-joa-it-admit-card-2026",
      "title": "HPRCA JOA IT Admit Card 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/hprca-joa-it-admit-card-2026/",
      "link": "https://sarkaricsc.com/hprca-joa-it-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/hprca-joa-it-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/hprca-joa-it-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/hprca-joa-it-admit-card-2026/"
      }
    },
    {
      "id": "bank-of-baroda-local-bank-officer-lbo-exam-date-2026",
      "title": "Bank of Baroda Local Bank Officer LBO Exam Date 2026:- OUT",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bank-of-baroda-local-bank-officer-lbo-exam-date-2026/",
      "link": "https://sarkaricsc.com/bank-of-baroda-local-bank-officer-lbo-exam-date-2026/",
      "actionUrl": "https://sarkaricsc.com/bank-of-baroda-local-bank-officer-lbo-exam-date-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bank-of-baroda-local-bank-officer-lbo-exam-date-2026/",
        "officialPdf": "https://sarkaricsc.com/bank-of-baroda-local-bank-officer-lbo-exam-date-2026/"
      }
    },
    {
      "id": "nainital-bank-specialist-officer-admit-card-2026",
      "title": "Nainital Bank Specialist Officer Admit Card 2026:- OUT",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/nainital-bank-specialist-officer-admit-card-2026/",
      "link": "https://sarkaricsc.com/nainital-bank-specialist-officer-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/nainital-bank-specialist-officer-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/nainital-bank-specialist-officer-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/nainital-bank-specialist-officer-admit-card-2026/"
      }
    },
    {
      "id": "upsssc-forensic-science-laboratory-admit-card-2026",
      "title": "UPSSSC Forensic Science Laboratory Admit Card 2026:- OUT",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsssc-forensic-science-laboratory-admit-card-2026/",
      "link": "https://sarkaricsc.com/upsssc-forensic-science-laboratory-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/upsssc-forensic-science-laboratory-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsssc-forensic-science-laboratory-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/upsssc-forensic-science-laboratory-admit-card-2026/"
      }
    },
    {
      "id": "upsssc-forest-guard-wildlife-guard-admit-card-2026",
      "title": "UPSSSC Forest Guard / Wildlife Guard Admit Card 2026:- OUT",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsssc-forest-guard-wildlife-guard-admit-card-2026/",
      "link": "https://sarkaricsc.com/upsssc-forest-guard-wildlife-guard-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/upsssc-forest-guard-wildlife-guard-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsssc-forest-guard-wildlife-guard-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/upsssc-forest-guard-wildlife-guard-admit-card-2026/"
      }
    },
    {
      "id": "opsc-assistant-horticulture-officer-admit-card-2026",
      "title": "OPSC Assistant Horticulture Officer Admit Card 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/opsc-assistant-horticulture-officer-admit-card-2026/",
      "link": "https://sarkaricsc.com/opsc-assistant-horticulture-officer-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/opsc-assistant-horticulture-officer-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/opsc-assistant-horticulture-officer-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/opsc-assistant-horticulture-officer-admit-card-2026/"
      }
    },
    {
      "id": "uppsc-pcs-interview-letter-2026",
      "title": "UPPSC PCS Interview Letter 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "12th Pass",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/uppsc-pcs-interview-letter-2026/",
      "link": "https://sarkaricsc.com/uppsc-pcs-interview-letter-2026/",
      "actionUrl": "https://sarkaricsc.com/uppsc-pcs-interview-letter-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/uppsc-pcs-interview-letter-2026/",
        "officialPdf": "https://sarkaricsc.com/uppsc-pcs-interview-letter-2026/"
      }
    },
    {
      "id": "utet-admit-card-2026",
      "title": "UTET Admit Card 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/utet-admit-card-2026/",
      "link": "https://sarkaricsc.com/utet-admit-card-2026/",
      "actionUrl": "https://sarkaricsc.com/utet-admit-card-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/utet-admit-card-2026/",
        "officialPdf": "https://sarkaricsc.com/utet-admit-card-2026/"
      }
    },
    {
      "id": "bpsc-project-manager-pre-exam-date-2026",
      "title": "BPSC Project Manager Pre Exam Date 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Active",
      "date": "Active",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/bpsc-project-manager-pre-exam-date-2026/",
      "link": "https://sarkaricsc.com/bpsc-project-manager-pre-exam-date-2026/",
      "actionUrl": "https://sarkaricsc.com/bpsc-project-manager-pre-exam-date-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/bpsc-project-manager-pre-exam-date-2026/",
        "officialPdf": "https://sarkaricsc.com/bpsc-project-manager-pre-exam-date-2026/"
      }
    }
  ],
  "results": [
    {
      "id": "nta-csir-ugc-net-e-certificate-2026",
      "title": "NTA CSIR UGC NET E Certificate 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/nta-csir-ugc-net-e-certificate-2026/",
      "link": "https://sarkaricsc.com/nta-csir-ugc-net-e-certificate-2026/",
      "actionUrl": "https://sarkaricsc.com/nta-csir-ugc-net-e-certificate-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/nta-csir-ugc-net-e-certificate-2026/",
        "officialPdf": "https://sarkaricsc.com/nta-csir-ugc-net-e-certificate-2026/"
      }
    },
    {
      "id": "csir-neist-driver-and-mts-result-2026",
      "title": "CSIR NEIST Driver and MTS Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "10th Pass",
      "tag": "10th Pass",
      "qualification": "10th Pass",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/csir-neist-driver-and-mts-result-2026/",
      "link": "https://sarkaricsc.com/csir-neist-driver-and-mts-result-2026/",
      "actionUrl": "https://sarkaricsc.com/csir-neist-driver-and-mts-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/csir-neist-driver-and-mts-result-2026/",
        "officialPdf": "https://sarkaricsc.com/csir-neist-driver-and-mts-result-2026/"
      }
    },
    {
      "id": "beml-executive-result-2026",
      "title": "BEML Executive Result 2026:- OUT",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "OUT",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/beml-executive-result-2026/",
      "link": "https://sarkaricsc.com/beml-executive-result-2026/",
      "actionUrl": "https://sarkaricsc.com/beml-executive-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/beml-executive-result-2026/",
        "officialPdf": "https://sarkaricsc.com/beml-executive-result-2026/"
      }
    },
    {
      "id": "hal-dt-and-mt-final-result-2026",
      "title": "HAL DT and MT Final Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/hal-dt-and-mt-final-result-2026/",
      "link": "https://sarkaricsc.com/hal-dt-and-mt-final-result-2026/",
      "actionUrl": "https://sarkaricsc.com/hal-dt-and-mt-final-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/hal-dt-and-mt-final-result-2026/",
        "officialPdf": "https://sarkaricsc.com/hal-dt-and-mt-final-result-2026/"
      }
    },
    {
      "id": "sssb-punjab-junior-scale-stenographer-result-2026",
      "title": "SSSB Punjab Junior Scale Stenographer Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "12th Pass",
      "tag": "12th Pass",
      "qualification": "12th Pass",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/sssb-punjab-junior-scale-stenographer-result-2026/",
      "link": "https://sarkaricsc.com/sssb-punjab-junior-scale-stenographer-result-2026/",
      "actionUrl": "https://sarkaricsc.com/sssb-punjab-junior-scale-stenographer-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/sssb-punjab-junior-scale-stenographer-result-2026/",
        "officialPdf": "https://sarkaricsc.com/sssb-punjab-junior-scale-stenographer-result-2026/"
      }
    },
    {
      "id": "upsssc-assistant-store-keeper-final-result-2026",
      "title": "UPSSSC Assistant Store Keeper Final Result 2026:- Released",
      "organization": "Staff Selection Commission (SSC)",
      "org": "Staff Selection Commission (SSC)",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/upsssc-assistant-store-keeper-final-result-2026/",
      "link": "https://sarkaricsc.com/upsssc-assistant-store-keeper-final-result-2026/",
      "actionUrl": "https://sarkaricsc.com/upsssc-assistant-store-keeper-final-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/upsssc-assistant-store-keeper-final-result-2026/",
        "officialPdf": "https://sarkaricsc.com/upsssc-assistant-store-keeper-final-result-2026/"
      }
    },
    {
      "id": "hprca-teacher-psychology-final-result-2026",
      "title": "HPRCA Teacher Psychology Final Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/hprca-teacher-psychology-final-result-2026/",
      "link": "https://sarkaricsc.com/hprca-teacher-psychology-final-result-2026/",
      "actionUrl": "https://sarkaricsc.com/hprca-teacher-psychology-final-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/hprca-teacher-psychology-final-result-2026/",
        "officialPdf": "https://sarkaricsc.com/hprca-teacher-psychology-final-result-2026/"
      }
    },
    {
      "id": "wbp-constable-final-result-2026",
      "title": "WBP Constable Final Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Police / Defense",
      "tag": "Police / Defense",
      "qualification": "Police / Defense",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/wbp-constable-final-result-2026/",
      "link": "https://sarkaricsc.com/wbp-constable-final-result-2026/",
      "actionUrl": "https://sarkaricsc.com/wbp-constable-final-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/wbp-constable-final-result-2026/",
        "officialPdf": "https://sarkaricsc.com/wbp-constable-final-result-2026/"
      }
    },
    {
      "id": "rbi-assistant-mains-result-2026",
      "title": "RBI Assistant Mains Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rbi-assistant-mains-result-2026/",
      "link": "https://sarkaricsc.com/rbi-assistant-mains-result-2026/",
      "actionUrl": "https://sarkaricsc.com/rbi-assistant-mains-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rbi-assistant-mains-result-2026/",
        "officialPdf": "https://sarkaricsc.com/rbi-assistant-mains-result-2026/"
      }
    },
    {
      "id": "nta-ugc-net-june-certificate-2026",
      "title": "NTA UGC NET June Certificate 2026",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Declared",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/nta-ugc-net-june-certificate-2026/",
      "link": "https://sarkaricsc.com/nta-ugc-net-june-certificate-2026/",
      "actionUrl": "https://sarkaricsc.com/nta-ugc-net-june-certificate-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/nta-ugc-net-june-certificate-2026/",
        "officialPdf": "https://sarkaricsc.com/nta-ugc-net-june-certificate-2026/"
      }
    },
    {
      "id": "neet-pg-result-2026",
      "title": "NEET PG Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/neet-pg-result-2026/",
      "link": "https://sarkaricsc.com/neet-pg-result-2026/",
      "actionUrl": "https://sarkaricsc.com/neet-pg-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/neet-pg-result-2026/",
        "officialPdf": "https://sarkaricsc.com/neet-pg-result-2026/"
      }
    },
    {
      "id": "rpsc-junior-legal-officer-result-2026",
      "title": "RPSC Junior Legal Officer Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rpsc-junior-legal-officer-result-2026/",
      "link": "https://sarkaricsc.com/rpsc-junior-legal-officer-result-2026/",
      "actionUrl": "https://sarkaricsc.com/rpsc-junior-legal-officer-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rpsc-junior-legal-officer-result-2026/",
        "officialPdf": "https://sarkaricsc.com/rpsc-junior-legal-officer-result-2026/"
      }
    },
    {
      "id": "mppsc-assistant-professor-commerce-result-2026",
      "title": "MPPSC Assistant Professor Commerce Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/mppsc-assistant-professor-commerce-result-2026/",
      "link": "https://sarkaricsc.com/mppsc-assistant-professor-commerce-result-2026/",
      "actionUrl": "https://sarkaricsc.com/mppsc-assistant-professor-commerce-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/mppsc-assistant-professor-commerce-result-2026/",
        "officialPdf": "https://sarkaricsc.com/mppsc-assistant-professor-commerce-result-2026/"
      }
    },
    {
      "id": "ibps-crp-po-mt-xvi-pre-result-2026",
      "title": "IBPS CRP PO MT XVI Pre Result 2026:- Released",
      "organization": "Banking Personnel Selection",
      "org": "Banking Personnel Selection",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/ibps-crp-po-mt-xvi-pre-result-2026/",
      "link": "https://sarkaricsc.com/ibps-crp-po-mt-xvi-pre-result-2026/",
      "actionUrl": "https://sarkaricsc.com/ibps-crp-po-mt-xvi-pre-result-2026/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/ibps-crp-po-mt-xvi-pre-result-2026/",
        "officialPdf": "https://sarkaricsc.com/ibps-crp-po-mt-xvi-pre-result-2026/"
      }
    },
    {
      "id": "rpsc-assistant-professor-result-2026-6",
      "title": "RPSC Assistant Professor Result 2026:- Released",
      "organization": "Central / State Govt",
      "org": "Central / State Govt",
      "category": "Graduate",
      "tag": "Graduate",
      "qualification": "Graduate",
      "totalPosts": "Check Notice",
      "posts": "Check Notice",
      "status": "Released",
      "lastDate": "Released",
      "date": "Released",
      "badgeColor": "bg-emerald-100 text-emerald-800 border-emerald-300",
      "url": "https://sarkaricsc.com/rpsc-assistant-professor-result-2026-6/",
      "link": "https://sarkaricsc.com/rpsc-assistant-professor-result-2026-6/",
      "actionUrl": "https://sarkaricsc.com/rpsc-assistant-professor-result-2026-6/",
      "links": {
        "actionLabel": "Apply Online",
        "actionUrl": "https://sarkaricsc.com/rpsc-assistant-professor-result-2026-6/",
        "officialPdf": "https://sarkaricsc.com/rpsc-assistant-professor-result-2026-6/"
      }
    }
  ],
  "answerKeys": [
    {
      "title": "SSC Stenographer Grade C & D Tentative Key 2026",
      "actionUrl": "https://ssc.gov.in",
      "category": "12th Pass",
      "link": "https://ssc.gov.in"
    },
    {
      "title": "RRB NTPC CEN 07/2025 Answer Key 2026",
      "actionUrl": "https://rrbapply.gov.in",
      "category": "12th Pass",
      "link": "https://rrbapply.gov.in"
    }
  ],
  "syllabus": [
    {
      "title": "UP Police Sub-Inspector (SI) Exam Pattern 2026",
      "actionUrl": "https://uppbpb.gov.in",
      "category": "Police / Defense",
      "link": "https://uppbpb.gov.in"
    },
    {
      "title": "RRB NTPC Graduate & UG Exam Syllabus 2026",
      "actionUrl": "https://rrbapply.gov.in",
      "category": "Graduate",
      "link": "https://rrbapply.gov.in"
    }
  ],
  "admissions": [
    {
      "title": "MCC NEET UG Counselling Round Registration",
      "actionUrl": "https://mcc.nic.in",
      "category": "Graduate",
      "link": "https://mcc.nic.in"
    },
    {
      "title": "NTA CUET PG Admission Schedule",
      "actionUrl": "https://cuet.nta.nic.in",
      "category": "Graduate",
      "link": "https://cuet.nta.nic.in"
    }
  ]
};

window.SARKARI_DATA = SARKARI_DATA;